# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'care-bears' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for care-bears
  pod 'AWSRekognition'
  pod 'AWSS3'
  pod 'AWSCore'
  pod 'AWSLambda'
  pod 'Swifter', '~> 1.4.5'

  target 'care-bearsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'care-bearsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
